name: Build App
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@vv4.1.1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        run: bun install
        run: bun run build